plugins {
    id 'multiloader-common'
}

configurations {
    commonJava{
        canBeResolved = true
    }
    commonResources{
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id"
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

def lootrCompat = project.hasProperty('lootr_compat') ? project.lootr_compat.toBoolean() : true

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
    if (!lootrCompat) {
        exclude 'com/meteorite/unsuspiciousblock/mixin/compat/lootr/**'
        exclude 'com/meteorite/unsuspiciousblock/plugin/lootr/**'
    }
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
    if (!lootrCompat) {
        exclude 'unsuspiciousblock.lootr.mixins.json'
        exclude 'META-INF/services/noobanidus.mods.lootr.common.api.filter.ILootrFilterProvider'
    }
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
    if (!lootrCompat) {
        exclude 'com/meteorite/unsuspiciousblock/mixin/compat/lootr/**'
        exclude 'com/meteorite/unsuspiciousblock/plugin/lootr/**'
    }
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    if (!lootrCompat) {
        exclude 'com/meteorite/unsuspiciousblock/mixin/compat/lootr/**'
        exclude 'com/meteorite/unsuspiciousblock/plugin/lootr/**'
        exclude 'unsuspiciousblock.lootr.mixins.json'
        exclude 'META-INF/services/noobanidus.mods.lootr.common.api.filter.ILootrFilterProvider'
    }
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}
