# Project
version=1.5.2
group=com.meteorite.unsuspiciousblock
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Unsuspicious Block
mod_author=meteoritel
mod_id=unsuspiciousblock
license=MIT
credits=
description=Add items that can analyze and extract loot from suspicious blocks without brushing.
minecraft_version_range=[1.21.1,1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.116.0+1.21.1
fabric_loader_version=0.17.0

# NeoForge
neoforge_version=21.1.195
neoforge_loader_version_range=[4,)

# Curios API
curios_version=9.5.1+1.21.1

# Artifacts
artifacts_version=13.2.1

# Trinkets
trinkets_version=3.10.0

# ModMenu
modmenu_version=11.0.4

# JEI
jei_version=19.21.2.313

# Lootr
lootr_version=1.21.1-1.11.37.121
lootr_fabric_version_id=eYyx60ld

lootr_compat_fabric=false
lootr_compat_neoforge=true

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
