modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]

modId="unsuspiciousblock"
version="${mod_version}"
displayName="${mod_name}"
authors="me_teorite/meteoritel"
description='''
添加一个解析可疑方块内部战利品的物品
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.unsuspiciousblock]] #optional
    # the modid of the dependency
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.unsuspiciousblock]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

